"""migration

Revision ID: 2ce982bc906f
Revises: d9a03c2ff1ca
Create Date: 2025-07-16 13:06:10.735922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ce982bc906f'
down_revision: Union[str, Sequence[str], None] = 'd9a03c2ff1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'content')
    # ### end Alembic commands ###
